FROM allennlp/allennlp:latest
COPY dev-requirements.txt .
COPY requirements.txt .

RUN pip install -r requirements.txt
RUN pip install -r dev-requirements.txt

COPY . .

VOLUME ["/docs","/site"]

ENTRYPOINT []