name: ci

on:
  push:
    branches:


      - master
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install -r requirements.txt
      - run: pip install -r dev-requirements.txt
      - run: python -m nltk.downloader wordnet
      - run: pip install mkdocs-material
      - run: make build-docs
      - run: mkdocs gh-deploy --force